// Game Configuration
export const CONFIG = {
  SAVE_KEY: "bountySaveV2",
  BASE_COOLDOWN_MS: 1000,
  TICK_MS: 1000,
  REDUCE_CD_MAX_COUNT: 20,
  SINGLE_TICK_THRESHOLD: 1,
  TICK_INTERVAL_TOLERANCE: 0.001,
  AUTOSAVE_INTERVAL_MS: 30000,
  TOAST_DURATION_MS: 3000,
  MAX_TOASTS: 5
};
