on: [push, pull_request, page_build]

jobs:
  deploy2nekoweb:
    runs-on: ubuntu-latest
    name: deploy2nekoweb
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: List files before deployment
        run: |
          echo "Current working directory: $(pwd)"
          echo "Files in current directory:"
          ls -la
          echo "Files in root:"
          ls -la /
          echo "GitHub workspace: $GITHUB_WORKSPACE"
          echo "Files in GitHub workspace:"
          ls -la $GITHUB_WORKSPACE
        
      - name: Prepare deployment files
        run: |
          # Create a clean deployment directory
          mkdir -p dist
          # Copy all files except git and github directories
          cp .gitignore dist/ 2>/dev/null || true
          cp index.html dist/ 2>/dev/null || true
          cp LICENSE dist/ 2>/dev/null || true
          cp README.md dist/ 2>/dev/null || true
          # Remove git and github directories from deployment
          echo "=== Deployment directory contents ==="
          ls -la dist/
          echo "=== Deployment directory file count ==="
          find dist/ -type f | wc -l
          echo "=== All files to be deployed ==="
          find dist/ -type f | sort
        
      - name: deploy2nekoweb
        uses: indiefellas/deploy2nekoweb@main
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-cookie: ${{ secrets.NEKOWEB_COOKIE }}
          nekoweb-domain: 'bountyidle.nekoweb.org'
          nekoweb-username: 'bountyidle'
          directory: 'dist'
